# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Init

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        StoreAsTar: true

  - job: Versions
    steps:
    
    - checkout: none
    - powershell: |
        New-Item -ItemType Directory -Force -Path $(Pipeline.Workspace)\Artifacts\ApiVersions
        New-Item -ItemType File -Force -Path $(Pipeline.Workspace)\Artifacts\ApiVersions\versions.dat
        # A dé-commenter quand le site web sera développé.
        Add-Content -Path $(Pipeline.Workspace)\Artifacts\ApiVersions\versions.dat -Value 'Toto=1.0.1'
    - task: PublishPipelineArtifact@1
      displayName: Publication du fichier
      inputs:
        targetPath: '$(Pipeline.Workspace)/Artifacts/ApiVersions/versions.dat'
        artifactName: 'ApiVersions'